// Side-effect import: each tool module calls registerTool() on load.
// Add new tools here as a single import line.
import './json-formatter';
import './base64';
import './unix-time';
import './uuid-ulid';
import './url-encode';
import './url-parser';
import './regexp-tester';
import './jwt-debugger';
import './yaml-json';
import './number-base';
import './text-diff';
import './json-csv';
import './hash';
import './sql-format';
import './sql-log-reconstructor';
import './string-case';
import './color';
import './random-string';
import './line-sort';
import './html-entity';
import './curl-to-code';
import './json-to-code';
// T3 tools
import './backslash-escape';
import './lorem-ipsum';
import './hex-ascii';
import './base64-image';
import './html-format';
import './css-format';
import './js-format';
import './xml-format';
import './scss-format';
import './html-preview';
import './markdown-preview';
import './html-to-jsx';
import './qr-code';
import './cron-parser';
